# Generated by Django 4.2.14 on 2024-08-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmanagertoken',
            name='key',
            field=models.CharField(default='275c377b1e7e4ef0b2a2bcacec197876', max_length=40, unique=True),
        ),
    ]
