# Generated by Django 4.2.14 on 2024-08-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_user', '0003_alter_buildingmanagertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmanagertoken',
            name='key',
            field=models.CharField(default='021d9b57ddee47509587f51d12f590d6', max_length=40, unique=True),
        ),
    ]
