# Generated by Django 4.2.14 on 2024-08-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_user', '0004_alter_buildingmanagertoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmanagertoken',
            name='key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
