# Generated by Django 4.2.14 on 2024-08-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=50, unique=True)),
                ('upload_day', models.DateField(auto_now_add=True)),
                ('charged_state', models.BooleanField()),
                ('battery', models.IntegerField()),
                ('guide_liquid', models.IntegerField()),
                ('right', models.BooleanField()),
                ('state', models.BooleanField()),
                ('location_floor', models.IntegerField()),
                ('start_x', models.IntegerField()),
                ('start_y', models.IntegerField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_building', to='buildings.building')),
            ],
        ),
    ]
