# Generated by Django 4.2.14 on 2024-08-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=15, unique=True)),
                ('building_name', models.TextField()),
                ('address', models.TextField()),
                ('min_floor', models.IntegerField(default=1)),
                ('max_floor', models.IntegerField(default=1)),
                ('firestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firestation', to='accounts.firestation')),
            ],
        ),
        migrations.CreateModel(
            name='Building_Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_floor', models.CharField(max_length=30, unique=True)),
                ('floor', models.IntegerField()),
                ('etc', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='building_image/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_building', to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Sprinkler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprinkler_id', models.CharField(max_length=40, unique=True)),
                ('sprinkler_x', models.IntegerField()),
                ('sprinkler_y', models.IntegerField()),
                ('building_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building_floor')),
            ],
        ),
        migrations.CreateModel(
            name='Bicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicon_id', models.CharField(max_length=30, unique=True)),
                ('bicon_x', models.IntegerField()),
                ('bicon_y', models.IntegerField()),
                ('building_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building_floor')),
            ],
        ),
    ]
