# Generated by Django 4.2.14 on 2024-08-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building_floor',
            name='fire',
            field=models.BooleanField(default=False),
        ),
    ]
