# Generated by Django 4.2.14 on 2024-08-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_buildingmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmanager',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buildingmanager',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
