# Generated by Django 4.2.14 on 2024-08-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_buildingmanager_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmanager',
            name='check_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buildingmanager',
            name='password',
            field=models.TextField(),
        ),
    ]
