# Generated by Django 4.2.14 on 2024-08-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_alter_buildingmanager_check_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingmanager',
            name='check_password',
        ),
        migrations.AddField(
            model_name='buildingmanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buildingmanager',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingmanager',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='buildingmanager',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='buildingmanager',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
