# Generated by Django 4.2.14 on 2024-08-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_buildingmanagertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingmanagertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuildingManager',
        ),
        migrations.DeleteModel(
            name='BuildingManagerToken',
        ),
    ]
