# Generated by Django 4.2.14 on 2024-08-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_remove_buildingmanagertoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.TextField(null=True),
        ),
    ]
