# Generated by Django 4.2.14 on 2024-08-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_fire_building_floor_fire'),
        ('fireissues', '0002_remove_fire_issue_fire_id_remove_fire_logs_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fire_issue',
            name='fire_x',
        ),
        migrations.RemoveField(
            model_name='fire_issue',
            name='fire_y',
        ),
        migrations.AddField(
            model_name='fire_issue',
            name='sprinkler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fire_sprinkler', to='buildings.sprinkler'),
            preserve_default=False,
        ),
    ]
