# Generated by Django 4.2.14 on 2024-08-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireissues', '0003_remove_fire_issue_fire_x_remove_fire_issue_fire_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fire_logs',
            name='firefighter_connect',
        ),
        migrations.RemoveField(
            model_name='fire_logs',
            name='guide_light',
        ),
    ]
